name:                Hydra
version:             1.0.0.0
github:              "graninas/Hydra"
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "Granin A.S. 2019"

description:
  Hydra is the project that allows to build multithreaded concurrent applications.
  Hydra is initially based on the Enecuum.Framework.

default-extensions:
- NoImplicitPrelude
- GADTs
- RankNTypes
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- ExplicitNamespaces
- TypeApplications
- ScopedTypeVariables
- TypeOperators
- TypeFamilies
- DataKinds
- FlexibleContexts
- FlexibleInstances
- PatternSynonyms
- PolyKinds
- DefaultSignatures
- ConstraintKinds
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf

dependencies:
- base >= 4.7 && < 5
- bytestring
- time-units
- network
- aeson
- aeson-pretty
- cereal
- mtl
- cryptonite
- base16-bytestring
- base58-bytestring
- base64-bytestring
- arithmoi
- directory
- filepath
- process
- extra
- time
- clock
- vector
- scientific
- containers
- random
- free
- iproute
- memory
- transformers
- template-haskell
- async
- text
- haskeline
- cryptohash-sha256
- bytestring-conversion
- newtype-generics
- lens
- universum
- fmt
- stm
- hslogger
- lens-aeson
- th-abstraction
- MonadRandom
- entropy
- validation
- silently
- uuid
- resourcet
- triplesec
- yaml
- hspec
- HUnit
- QuickCheck
- hspec-contrib
- newtype-generics
- regex-posix
- safe-exceptions

library:
  source-dirs:
    - src
  ghc-options:
  - -Wall

executables:
  perf-test-app:
    main:                Main.hs
    source-dirs:         app/PerfTestApp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - Hydra
  meteror-counter-app:
    main:                Main.hs
    source-dirs:         app/MeteorCounter
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - Hydra


tests:
  functional-tests:
    main: Spec.hs

    dependencies:
    - Hydra
    source-dirs:
    - test/spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
